version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Nairobi
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
