CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL CHECK(char_length(name) BETWEEN 2 AND 120),slug text NOT NULL UNIQUE,league text NOT NULL,price_kes integer CHECK(price_kes IS NULL OR price_kes>=0),status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','out_of_stock','active')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE product_variants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,kit_type text NOT NULL CHECK(kit_type IN('home','away','third')),size text NOT NULL CHECK(size IN('S','M','L','XL')),stock integer NOT NULL DEFAULT 0 CHECK(stock>=0),image_key text,UNIQUE(product_id,kit_type,size));
CREATE TABLE orders(id uuid PRIMARY KEY,customer_name text NOT NULL,phone text NOT NULL,status text NOT NULL CHECK(status IN('pending','payment_pending','paid','cancelled','fulfilled','refunded')),provider_reference text UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,product_variant_id uuid NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,quantity integer NOT NULL CHECK(quantity BETWEEN 1 AND 10),unit_price_kes integer NOT NULL CHECK(unit_price_kes>=0));
CREATE TABLE admins(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL UNIQUE,password_hash text NOT NULL,mfa_secret_encrypted bytea,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_log(id bigserial PRIMARY KEY,admin_id uuid REFERENCES admins(id),action text NOT NULL,entity_type text NOT NULL,entity_id uuid,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX products_status_idx ON products(status);CREATE INDEX variants_product_idx ON product_variants(product_id);CREATE INDEX orders_created_idx ON orders(created_at DESC);

