"use client";
import { useMemo, useState } from "react";
import { products } from "@/lib/products";
export default function Home(){
 const [query,setQuery]=useState(""); const [league,setLeague]=useState("All clubs"); const [slides,setSlides]=useState<Record<string,number>>({});
 const leagues=["All clubs",...Array.from(new Set(products.map(p=>p.league)))];
 const visible=useMemo(()=>products.filter(p=>(league==="All clubs"||p.league===league)&&p.name.toLowerCase().includes(query.toLowerCase())),[league,query]);
 return <main>
  <div className="notice">Free delivery during our early-access launch · Nairobi orders only</div>
  <header className="site-header"><a href="#top" className="brand"><img src="/emk-prints-logo.png" alt="EMK PRINTS"/></a><nav><a href="#shop">Shop</a><a href="#how">How it works</a><a href="#returns">Returns</a></nav><a className="whatsapp" href="https://wa.me/254710585456" target="_blank" rel="noreferrer">WhatsApp us</a></header>
  <section id="top" className="hero"><div className="hero-copy"><p className="kicker">2026/27 COLLECTION PREVIEW</p><h1>Your club.<br/><em>Your colours.</em></h1><p>Home, away and third kits from the clubs you follow. Browse the preview now and message us when your size lands.</p><a className="cta" href="#shop">Browse jerseys <span>↓</span></a></div><div className="hero-panel"><p>EARLY ACCESS</p><strong>13</strong><span>clubs arriving soon</span><div className="size-row"><b>S</b><b>M</b><b>L</b><b>XL</b></div><small>No payment is collected until stock and pricing are confirmed.</small></div></section>
  <section id="shop" className="shop-section"><div className="shop-heading"><div><p className="kicker">THE LINE-UP</p><h2>Find your club</h2></div><p>Every product includes home, away and third-kit previews. Real shop photography will replace these references when stock arrives.</p></div>
   <div className="shop-controls"><label className="search"><span>Search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Club name"/></label><div className="filters">{leagues.map(x=><button className={league===x?"active":""} key={x} onClick={()=>setLeague(x)}>{x}</button>)}</div></div>
   <div className="product-grid">{visible.map(product=>{const active=slides[product.slug]??0;const kit=product.kits[active];return <article className="product-card" key={product.slug}><div className="product-image"><img src={kit.image} alt={`${product.name} ${kit.label} kit preview`} loading="lazy"/><span className="stock-badge">Out of stock</span><div className="slide-tabs">{product.kits.map((k,i)=><button key={k.label} className={i===active?"active":""} onClick={()=>setSlides(v=>({...v,[product.slug]:i}))}>{k.label}</button>)}</div></div><div className="product-info"><div><p>{product.league}</p><h3>{product.name}</h3></div><span>Price coming soon</span></div><div className="sizes"><span>Sizes</span>{["S","M","L","XL"].map(s=><b key={s}>{s}</b>)}</div><a className="notify" href={`https://wa.me/254710585456?text=${encodeURIComponent(`Hi EMK PRINTS, please notify me when the ${product.name} ${kit.label} kit is available.`)}`} target="_blank" rel="noreferrer">Ask about this jersey</a></article>})}</div>{!visible.length&&<p className="empty">No club matches your search.</p>}
  </section>
  <section id="how" className="steps"><p className="kicker">SIMPLE BY DESIGN</p><h2>From preview to match day.</h2><div><article><span>01</span><h3>Choose your club</h3><p>View the home, away and third-kit references in one card.</p></article><article><span>02</span><h3>Confirm on WhatsApp</h3><p>We confirm the exact design, size, price and availability before payment.</p></article><article><span>03</span><h3>Receive your order</h3><p>Early-access delivery is free while we serve our current local customer area.</p></article></div></section>
  <section id="returns" className="returns"><div><p className="kicker">RETURNS & EXCHANGES</p><h2>Something wrong with your order?</h2></div><p>Message us on WhatsApp with clear photographs of the product received, your order number, and your payment-confirmation message. We’ll review the issue and guide you through the next step.</p><a href="https://wa.me/254710585456" target="_blank" rel="noreferrer">Start a WhatsApp message →</a></section>
  <footer><a className="brand" href="#top"><img src="/emk-prints-logo.png" alt="EMK PRINTS"/></a><p>Football jerseys, clearly presented.</p><div><a href="https://wa.me/254710585456">+254 710 585 456</a><span>© 2026 EMK PRINTS</span></div></footer>
 </main>
}
