use actix_web::{HttpResponse,web};use validator::Validate;use crate::{error::ApiError,models::{LoginInput,OrderInput,Product,ProductInput},state::AppState};
pub fn configure(cfg:&mut web::ServiceConfig){cfg.route("/health",web::get().to(health)).route("/v1/products",web::get().to(products)).route("/v1/orders",web::post().to(create_order)).route("/v1/admin/login",web::post().to(login)).route("/v1/admin/products",web::post().to(create_product)).route("/v1/payments/webhook",web::post().to(payment_webhook));}
async fn health()->HttpResponse{HttpResponse::Ok().json(serde_json::json!({"status":"ok"}))}
async fn products(state:web::Data<AppState>)->Result<HttpResponse,ApiError>{let rows=sqlx::query_as::<_,Product>("SELECT id,name,slug,league,price_kes,status,created_at,updated_at FROM products WHERE status <> 'draft' ORDER BY name").fetch_all(&state.pool).await.map_err(|_|ApiError::Internal)?;Ok(HttpResponse::Ok().json(rows))}
async fn create_order(state:web::Data<AppState>,body:web::Json<OrderInput>)->Result<HttpResponse,ApiError>{body.validate().map_err(|_|ApiError::Validation)?;if body.items.is_empty(){return Err(ApiError::Validation)}let id=uuid::Uuid::new_v4();sqlx::query("INSERT INTO orders(id,customer_name,phone,status) VALUES($1,$2,$3,'pending')").bind(id).bind(body.customer_name.trim()).bind(body.phone.trim()).execute(&state.pool).await.map_err(|_|ApiError::Internal)?;Ok(HttpResponse::Created().json(serde_json::json!({"order_id":id,"status":"pending"})))}
async fn login(body:web::Json<LoginInput>)->Result<HttpResponse,ApiError>{body.validate().map_err(|_|ApiError::Validation)?;Err(ApiError::Unauthorized)}
async fn create_product(_state:web::Data<AppState>,body:web::Json<ProductInput>)->Result<HttpResponse,ApiError>{body.validate().map_err(|_|ApiError::Validation)?;Err(ApiError::Unauthorized)}
async fn payment_webhook(_state:web::Data<AppState>,bytes:web::Bytes)->Result<HttpResponse,ApiError>{if bytes.len()>64*1024{return Err(ApiError::Validation)}Ok(HttpResponse::Accepted().finish())}

